### ISSUE TITLE
Integrating OpenRMF with my robot using this template

### ISSUE THREAD

**Issue by linhns** [open-rmf/fleet_adapter_template#9]
Hi @Yadunund  and OpenRMF team, apologies if this is the wrong place to ask for support regarding this template. The support guideline link issue in #8 stills persists. 

**Environment:**
`Ubuntu 20.04` + `ROS2 Foxy`

I'm trying to integrate my robot that works with ROS2 using this template. Can I check if the template works with the Foxy binaries of rmf?

If it works, what else do I need to run beside the fleet adapter node in the step 3 of the `README`? Clearly that one node is not enough.

In step 2 of the `README`, how can I get the **reference_coordinates**? I cannot find any mentioning of it on the website.

**Comment by Yadunund** [comment]
Hi @linhns 

Sadly, we're not maintaining a `foxy` version of the template due to resource constraints. But as mentioned in the linked PR, we'd be happy to receive a contribution for a `foxy` branch. The template will work with the `galactic` binaries and should work with the `humble` ones too but this has not been tested yet. 

> If it works, what else do I need to run beside the fleet adapter node in the step 3 of the README? Clearly that one node is not enough.

The adapter is the bridge between RMF systems and the fleet. It may be launched along with other core RMF nodes. Say you were running a real robot in the physical `office` world, you would replace [these lines of code](https://github.com/open-rmf/rmf_demos/blob/6533f32a5e5387ddc06d402957eb7adfc8e33d11/rmf_demos/launch/office.launch.xml#L15-L29) with commands to launch your adapter. 

> In step 2 of the README, how can I get the reference_coordinates? I cannot find any mentioning of it on the website.

The idea is to provide two lists of equal length with [x,y] coordinates. The `rmf` list contains coordinates in the RMF coordinate frame. Assuming you create your navigation graphs using `rmf_traffic_editor`, these would be the x & y coordinates in meters for a waypoint
![image](https://user-images.githubusercontent.com/13482049/170872466-26efe85f-f663-4f03-b659-ad1e666bc989.png)

The corresponding coordinate in the`robot` list would the position of the same waypoint read from the robot's API. So you would drive the robot to that same location in the physical world, and read the reported coordinates. It is recommended to record a minimum of 4 such corresponding coordinates for `nudged` to perform its transformation.

**Comment by linhns** [comment]
Hi @Yadunund 
Thanks for answering, it makes my understanding better. As I'm short of time, is there a way for me to not implement docking abilities [here](https://github.com/open-rmf/fleet_adapter_template/blob/9efc0d4d0f178840c096c736aa611b9d8a481f2b/fleet_adapter_template/fleet_adapter_template/RobotCommandHandle.py#L284) as well as [here](https://github.com/open-rmf/fleet_adapter_template/blob/main/fleet_adapter_template/fleet_adapter_template/RobotClientAPI.py#L67) and RMF would still be able to perform the Loop Task as I don't see any docking related logic there?

**Comment by Yadunund** [comment]
Yup that would be fine. Just make sure you done have any docking waypoints on the graph.

**Comment by linhns** [comment]
> The idea is to provide two lists of equal length with [x,y] coordinates. The rmf list contains coordinates in the RMF coordinate frame. Assuming you create your navigation graphs using rmf_traffic_editor, these would be the x & y coordinates in meters for a waypoint
@Yadunund Is there a requirement that RMF and our robot coords must have the same convention (x-axis to the right, y-axis down) as my coworker is asking?

**Comment by Yadunund** [comment]
For the sake of completeness, I'll answer you last question. 
No, there is no requirement for your robot's coordinate conventions to match RMF's. The reference coordinate approach detailed above will compute the scale, rotation and translation transforms between the two coordinate systems.
